server:
  verbosity: 2
  use-syslog: no

  interface: 0.0.0.0
  port: 53

  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes

  access-control: 0.0.0.0/0 allow

  so-rcvbuf: 0
  so-sndbuf: 0

  cache-min-ttl: 300
  cache-max-ttl: 86400
  prefetch: yes

forward-zone:
  name: "."
  forward-addr: 1.1.1.1
  forward-addr: 8.8.8.8
